name: Twitter sentiment analysis
description: Deployment of pre-trained model for sentiment analysis of Tweets.
author: Cloudera Inc.
date: '2023-01-17'
specification_version: "0.1"
prototype_version: "1.0"

runtimes:

  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard

tasks:

  - type: start_application
    subdomain: dataviz-twitter-sentiment
    script: /opt/vizapps/tools/arcviz/startup_app.py
    runtimes:
      - editor: Workbench
        kernel: Cloudera Data Vizualiation
        edition: CDV 7.0.4
